sudo: required
services:
  - docker

before_install:
  - docker build -t marshallrhodesfox/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true marshallrhodesfox/docker-react npm run 

deploy:
  provider: elasticbeanstack
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
